### ISSUE TITLE
Exception when including watigiri with watir 6.15

### ISSUE THREAD

**Issue by kribri** [titusfortner/watigiri#10]
Just including watigiri (0.6.1) ("require 'watigiri") with watir 15.0 installed leads to the exception below:

> Minitest::UnexpectedError: NameError: uninitialized constant Watir::Locators::TextArea::Locator
> Did you mean?  Watir::Locators
>     C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:147:in `<class:TextArea>'
>     C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:146:in `<module:Locators>'
>     C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:15:in `<module:Watigiri>'
>     C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:1:in `<top (required)>'
>     C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri.rb:8:in `require'
>     C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri.rb:8:in `<top (required)>'
>     C:/Users/olga/Documents/workspace/TMPS-TAF/Tests/Widgets/sandbox_test.rb:25:in `require'
>     C:/Users/olga/Documents/workspace/TMPS-TAF/Tests/Widgets/sandbox_test.rb:25:in `test_login_via_ui'
> C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:147:in `<class:TextArea>'
> C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:146:in `<module:Locators>'
> C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:15:in `<module:Watigiri>'
> C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri/locators/element/locator.rb:1:in `<top (required)>'
> C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri.rb:8:in `require'
> C:/Software/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watigiri-0.6.1/lib/watigiri.rb:8:in `<top (required)>'
> C:/...._test.rb:25:in `require'

**Comment by titusfortner** [comment]
Fixed with 0.7.0 release
