### ISSUE TITLE
Watir 6.12: undefined method `locator_namespace=' for Watir:Module (NoMethodError)

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/watigiri#6]
The gem needs to be updated to work with the locator namespace changes in Watir 6.12:

```
ruby/gems/2.3.0/gems/watigiri-0.4.0/lib/watigiri.rb:11:in `<top (required)>': undefined method `locator_namespace=' for Watir:Module (NoMethodError)
```

Thanks!

**Comment by titusfortner** [comment]
Thanks for the ping. 
I actually spent some time making sure all of the watirspecs are passing for it as well.
0.6.0 should be mostly good.
A couple issues that will be resolved in Watir 6.13.
Let me know if you have any issues with it.
