### ISSUE TITLE
Ignore Regex Values

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/watigiri#7]
Allow users to set `Watigiri.ignore_regex` so that it doesn't process regular expressions by default.

**Comment by kapoorlakshya** [comment]
Is there a performance improvement/regression with `Watigiri.ignore_regex` to true? Wondering what the use case for this is.

**Comment by titusfortner** [comment]
No, the performance improvement is theoretically from using Nokogiri in locating elements matching. But, Justin did some optimizations in the Watir code that makes this slightly less important. The question is whether someone might want to use watigiri for its `#text!` functionality but not for its regular expression locating functionality. Right now if you require `watigiri` there's no way not to use it in locating elements.

**Comment by kapoorlakshya** [comment]
> someone might want to use watigiri for its #text! functionality but not for its regular expression locating functionality. 

Ah, I see. Is `watigiri`'s Regex location approach (slightly?) faster than Watir's approach? What's the trade off if we use `watigiri` for Regex?

**Comment by titusfortner** [comment]
Watir takes the locators provided and tries to build a single XPath expression. For some locators, it builds an XPath expression that will return a collection of potentially matching elements and then iterate through them to find the desired one(s). Evaluating each potential match is a wire call. If you are iterating over more than a handful of elements, it is likely faster (especially when running remotely) to get all of the relevant html and use nokogiri to iterate locally.

**Comment by kapoorlakshya** [comment]
Thanks for the explanation. That makes a lot more sense now.

**Comment by titusfortner** [comment]
Fixed with 0.7.0 release
