### ISSUE TITLE
Watir 6.14 - private method `switch!' called for #<Watir::FramedDriver:0x0000000c4859c0> (NoMethodError)

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/watigiri#9]
Getting this error with watir v6.14 and watigiri v0.6.0 @ IEDriverServer v3.14 when attempting to interact with an element inside an iFrame: 

```private method `switch!' called for #<Watir::FramedDriver:0x0000000c4859c0> (NoMethodError)```

**EDIT**: Looks like it is `public` in watir, but `private` in watigiri:

```
# watigiri-0.6.0/lib/extensions/watir/iframe.rb:15
class FramedDriver
    private

    alias watir_switch! switch!
    def switch!
      @browser.doc = nil
      watir_switch!
    end
  end # FramedDriver
```

**Comment by titusfortner** [comment]
Ooh, my watir refactor broke something. Thanks for the heads up

**Comment by titusfortner** [comment]
fixed, thanks.
